/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./components/common/AppAvatar.vue')['default']
    AppCard: typeof import('./components/common/AppCard.vue')['default']
    AppContainer: typeof import('./components/layout/AppContainer.vue')['default']
    AppEmpty: typeof import('./components/common/AppEmpty.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLoading: typeof import('./components/common/AppLoading.vue')['default']
    AppLogo: typeof import('./components/common/AppLogo.vue')['default']
    AppMainLayout: typeof import('./components/layout/AppMainLayout.vue')['default']
    AppPageHeader: typeof import('./components/layout/AppPageHeader.vue')['default']
    AppPagination: typeof import('./components/common/AppPagination.vue')['default']
    AppSearch: typeof import('./components/common/AppSearch.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ClientSelect: typeof import('./components/common/ClientSelect.vue')['default']
    DiaryCalendar: typeof import('./components/diary/DiaryCalendar.vue')['default']
    DiaryCard: typeof import('./components/diary/DiaryCard.vue')['default']
    DiaryList: typeof import('./components/diary/DiaryList.vue')['default']
    DiaryMoodChart: typeof import('./components/diary/DiaryMoodChart.vue')['default']
    DiaryTabs: typeof import('./components/diary/DiaryTabs.vue')['default']
    HomeBanner: typeof import('./components/home/HomeBanner.vue')['default']
    HomeFeatureGrid: typeof import('./components/home/HomeFeatureGrid.vue')['default']
    HomeIntroCard: typeof import('./components/home/HomeIntroCard.vue')['default']
    HomeProfileCard: typeof import('./components/home/HomeProfileCard.vue')['default']
    HomeQuickNav: typeof import('./components/home/HomeQuickNav.vue')['default']
    HomeTagCard: typeof import('./components/home/HomeTagCard.vue')['default']
    LineChart: typeof import('./components/chart/LineChart.vue')['default']
    LoadingOverlay: typeof import('./components/LoadingOverlay.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    MomentCard: typeof import('./components/moment/MomentCard.vue')['default']
    MomentFilter: typeof import('./components/moment/MomentFilter.vue')['default']
    MomentGrid: typeof import('./components/moment/MomentGrid.vue')['default']
    MomentToolbar: typeof import('./components/moment/MomentToolbar.vue')['default']
    MomentVideoCard: typeof import('./components/moment/MomentVideoCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NQrCode: typeof import('naive-ui')['NQrCode']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PieChart: typeof import('./components/chart/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserContact: typeof import('./components/user/UserContact.vue')['default']
    UserInfo: typeof import('./components/user/UserInfo.vue')['default']
    UserResume: typeof import('./components/user/UserResume.vue')['default']
    UserSkill: typeof import('./components/user/UserSkill.vue')['default']
    UserTags: typeof import('./components/user/UserTags.vue')['default']
    WorkCard: typeof import('./components/work/WorkCard.vue')['default']
    WorkChart: typeof import('./components/work/WorkChart.vue')['default']
    WorkList: typeof import('./components/work/WorkList.vue')['default']
    WorkStats: typeof import('./components/work/WorkStats.vue')['default']
    WorkTabs: typeof import('./components/work/WorkTabs.vue')['default']
  }
}
